### ISSUE TITLE
关于libglad.a

### ISSUE THREAD

**Issue by 2565904536** [yocover/start-learning-opengl#1]
我在编译教程实例时编译器报错:
lib/libglad.a(glad.o):glad.c:(.text+0x273): undefined reference to `__mingw_free'
我使用的编译器是Min-GW-w64
如果单独下载glad.c并编译后导入到lib中替换原来的libglad.a编译实例时就不会报错
并且程序能正常运行

**Comment by yocover** [comment]
感谢您提出的问题，glad是需要您在自己本地进行编译后才可以使用的，总之能运行就行，建议最好还是使用比较完善的IDE集成开发工具，尽可能的避免一些错误的出现

**Comment by yocover** [comment]
> 我在编译教程实例时编译器报错： lib/libglad.a(glad.o):glad.c:(.text+0x273): undefined reference to `__mingw_free' 我使用的编译器是 Min-GW-w64 如果单独下载glad.c并编译后导入到lib中替换原来的libglad.a编译实例时就不会 并且程序能正常运行

您需要在本地进行编译后才可以使用的，总之能运行就行，建议使用比较完善的 IDE 集成开发工具，避免出现一些错误
