### ISSUE TITLE
makefile问题

### ISSUE THREAD

**Issue by Hanflipped** [yocover/start-learning-opengl#4]
makefile文件有错误
CLEAN_SRC		:= src \ $(dir) \*.o #// 删除所有.o文件

OUTPUTMAIN	:= $(call FIXPATH,$(OUTPUT) \ $(MAIN))

这两句的斜杠都弄反了

**Comment by yocover** [comment]
> makefile文件有错误 CLEAN_SRC := src \ $(dir) *.o #// 删除所有.o文件
> 
> OUTPUTMAIN := (callFIXPATH,(OUTPUT) \ $(MAIN))
> 
> 这两句的斜杠都弄反了

区分windwos和linux系统下
